const fs = require('fs')
const csv = fs.readFileSync('ContentFinderCondition.csv').toString()

const lines = csv.replace(/\r\n/g, '\n').split('\n')
let data = []

const partySizeList = [null, null, 4, 8, 24]

const types = [
  null,
  null,
  '迷宫挑战',
  null, // 行会令
  '讨伐歼灭战',
  '大型任务'
]

types[28] = '绝境战'

const ids = lines[0].split(',')
const title = lines[1].split(',')
const map = new Map()
for (let i = 0; i < ids.length; i++) {
  map.set(title[i], parseInt(ids[i]))
}

for (const line of lines) {
  const cols = line.split(',')
  const index = cols.shift()
  const instanceType = cols[map.get('ContentLinkType')]
  const partyTypeId = cols[map.get('ContentMemberType')]
  const level = cols[map.get('ClassJobLevel{Required}')]
  const maxLevel = cols[map.get('ClassJobLevel{Sync}')]
  const ilvMin = cols[map.get('ItemLevel{Required}')]
  const ilvMax = cols[map.get('ItemLevel{Sync}')]
  const underSized = cols[map.get('AllowUndersized')]
  const name = cols[map.get('Name')]
  const typeId = cols[map.get('ContentType')]
  const banner = cols[map.get('Image')]
  const sortKey = cols[map.get('SortKey')]

  if (!name) continue
  if (instanceType !== '1') continue
  if (!types[typeId]) continue
  if (name.match(/^"活动/)) continue

  data.push({
    index: parseInt(index),
    partySize: partySizeList[partyTypeId],
    level: parseInt(level),
    maxLevel: parseInt(maxLevel),
    ilvMax: parseInt(ilvMax),
    ilvMin: parseInt(ilvMin),
    underSized: underSized.toLowerCase() === 'true',
    name: JSON.parse(name),
    type: types[typeId],
    typeId: parseInt(typeId),
    banner: parseInt(banner),
    sort: parseInt(sortKey)
  })
}

data = data.sort((a, b) => {
  if (a.typeId === b.typeId) {
    return a.sort - b.sort
  } else {
    return a.typeId - b.typeId
  }
})

const result = []
result.push('/* eslint-disable */')
result.push('// generated by instanceList.js')
result.push('module.exports = [')
result.push(data.map(x => JSON.stringify(x)).join(',\n'))
result.push(']')

fs.writeFileSync('../../docs/.vuepress/theme/duty.js', result.join('\n'))

for (const item of data) {
  const filename = `../../docs/duty/${item.index}.md`
  if (!fs.existsSync(filename)) {
    fs.writeFileSync(
      filename,
      `---
underConstruction: true
---
<!-- 攻略完成后请移除本行及以上内容 -->
# ${item.name}

<UnderConstruction />`
    )
  }
}
