name: Updates

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: 安装 pnpm
        uses: pnpm/action-setup@v6
      - name: 安装 Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      - name: 构建网站
        run: pnpm test && pnpm build
      - name: 导出部署密钥
        run: echo "$DEPLOY_KEY" > ci/deploy-key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      - name: 运行部署脚本
        run: |
          chmod +x ./ci/deploy.sh
          ./ci/deploy.sh
        env:
          UPDATE_KEY: ${{ secrets.UPDATE_KEY }}
      - name: 触发网站更新
        run: curl -XPOST $GITPAGES_UPDATE_URL
        env:
          GITPAGES_UPDATE_URL: ${{ secrets.GITPAGES_UPDATE_URL }}
